from flask import request, redirect
from flask_restplus import Resource

from app.src.short_urls.dto import ShorterURLDto
from app.src.short_urls.service import save_new_shorter, get_most_frequent_url, get_a_url

api = ShorterURLDto.api
_shorterURL = ShorterURLDto.shorterURL


@api.route('/')
class ShorterURLList(Resource):
    @api.doc('list_of_registered_users')
    @api.marshal_list_with(_shorterURL, envelope='data')
    def get(self):
        """List all registered users"""
        return get_most_frequent_url()

    @api.doc('create a new shorter URL')
    @api.expect(_shorterURL, validate=True)
    @api.marshal_with(_shorterURL)
    def post(self):
        """Creates a new User """### Run the Project 
        data = request.json
        return save_new_shorter(data=data)


@api.route('/<shorter_url>')
@api.param('shorter_url', 'Shorter URL generated by the system')
@api.response(404, 'Shorter url not found.')
class ShorterURL(Resource):
    @api.doc('get a shorter url')
    def get(self, shorter_url):
        """get a user given its identifier"""
        url = get_a_url(shorter_url)
        if not url:
            api.abort(404)
        return redirect(url.original_url)
